import Head from "next/head";
import Image from "next/image";
import React from "react";
import { Footer } from "src/components/footer/index.jsx";
import { Header } from "src/components/header/index";
import styles from "src/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <div className="flex relative justify-center content-center items-center ">
          <div className="container p-0 m-0 ">
            <div className="flex flex-wrap items-center ">
              <div className="p-0 m-0 w-full ">
                <Image
                  src="/vercel.svg"
                  alt=""
                  quality={100}
                  width={1920}
                  height={1080}
                />
                <Image
                  src="/vercel.svg"
                  alt=""
                  quality={100}
                  width={1920}
                  height={1080}
                />
              </div>
            </div>
          </div>
        </div>
      </main>

      <Footer />
      <footer className={styles.footer}>
        Powered by{" "}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </footer>
    </div>
  );
}
